danceability('../../../../../audio/recorded/beethoven.wav')
danceability('../../../../../audio/recorded/carreras.wav')
danceability('../../../../../audio/recorded/dik.wav')
danceability('../../../../../audio/recorded/techno.wav')
danceability('../../../../../audio/recorded/world_2.wav')
