#!/usr/bin/python

Import('ran_scripts')
if 'doc/SConscript' in ran_scripts: Return()
ran_scripts.append('doc/SConscript')

import os, sys, glob
from os.path import join, split

Import('source_tree_path', 'env', 'build_sh_cmd', 'conf')
env = env.Clone()
bld_dir = join(source_tree_path,'build','doc')

### Run dependencies ###
# Set DESTDIR to the build folder so we can put the p-bindings there to build the doc
conf.DESTDIR = bld_dir
conf.PREFIX = 'temp-python-bindings'
SConscript(join('..','src','python','SConscript'))
Import('python_install_path', 'python_install_alias')


# sphinx documentation
def generate_sphinx_doc(target, source, env):
    sys.path = [ python_install_path ] + sys.path
    print 'Hello,', python_install_path

sphinxdoc_cmd = build_sh_cmd(env, 'sphinxdoc_target', 'doc/build_sphinx_doc.sh', local=False)
AlwaysBuild(sphinxdoc_cmd)
env.Depends(sphinxdoc_cmd, 'python_install')
env.Alias('doc', sphinxdoc_cmd)
