#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import print_function

import distutils.sysconfig
import os,  sys


def options(ctx):
    ctx.load('python')


def configure(ctx):
    ctx.load('compiler_c python')
    ctx.check_python_version((2,7,0))
    if int(ctx.env.PYTHON_VERSION[0]) == 2:
        print ('→ Configuring for python2')
    else:
        print ('→ Configuring for python3')
    
    ctx.check_python_headers()
    ctx.check_python_module('numpy')

def adjust(objs, path):
    return [ '%s/%s' % (path, obj) for obj in objs ]

def build(ctx):
    print('→ building from ' + ctx.path.abspath())
    if sys.platform.startswith('linux'):
        ctx.env['pyext_PATTERN'] = "%s.so"
        python_dir = str(ctx.env['PYTHONDIR'])
        python_dir = python_dir.replace ('3/', str(ctx.env['PYTHON_VERSION'])+'/', 1)
        ctx.env['PYTHONDIR'] = python_dir
    #print(ctx.env['pyext_PATTERN'])
    # gets the path from the active virtualenv
    PYLIB = distutils.sysconfig.get_python_lib()
    #print('-'*100)
    #print('ctx.env', ctx.env)
    #print('-'*100)
    NUMPY_INCPATH = [ # importable numpy path
                      __import__('numpy').get_include(),
                      # virtualenv path
                      os.path.join(PYLIB, 'numpy', 'core', 'include'),
                      # system python path
                      os.path.join(ctx.env.PYTHONDIR, 'numpy', 'core', 'include') ]

    pybindings = ctx.shlib(
        source   = ctx.path.ant_glob('essentia.cpp parsing.cpp pytypes/*.cpp'),
        target   = '_essentia',
        features = 'pyext',
        includes = NUMPY_INCPATH + [ '.', 'pytypes' ] + adjust(ctx.env.INCLUDES, '..'),
        cxxflags= [ '-w','-std=c++11', '-msse2','-Wall', \
            '-Wno-misleading-indentation', \
            '-Wno-unused-result',\
            '-fno-strict-aliasing',\
            '-fPIC', '-fvisibility=hidden'],
        lib = 'essentia', 
        libpath = ['..'], 
        install_path = '${PYTHONDIR}/essentia'
        #use      = 'essentia ' #+ ctx.env.USES
    )

    ctx.install_files('${PYTHONDIR}', ctx.path.ant_glob('essentia/**/*.py'),
                      relative_trick=True)
