import { useCallback, useEffect, useRef, useState } from 'react'
import type { ChangeEvent, RefObject } from 'react'
import { Activity, ArrowDownToLine, ArrowLeft, ArrowRight, AudioLines, Check, ChevronRight, Clock3, FolderOpen, Headphones, LayoutDashboard, Library, Loader2, Moon, MoreHorizontal, Music2, Pause, Play, Plus, RefreshCw, Search, Settings2, SlidersHorizontal, Sparkles, Sun, Trash2, Upload, Volume2, X } from './icons'
import type { LucideIcon } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import WaveSurfer from 'wavesurfer.js'
import { api, number, send, time } from './api'
import type { Dimension, Profile, Score, Settings, Stats, Track } from './types'

const labels = ['非常舒适', '比较舒适', '一般', '比较吵', '非常吵']
const factors = ['音量过大', '高频刺耳', '鼓点密集', '编曲过于激烈', '人声过于尖锐', '动态变化突然', '其他']
const dimensionLabels: Record<Dimension, string> = { aggressive: '音乐激烈程度', unrelaxed: '放松程度反向指标', loudness: '整体响度', brightness: '高频刺激代理', density: '瞬态密集程度', flatness: '噪声状频谱代理' }
const colors = ['#91c8b0', '#91bab7', '#a5abd3', '#c2a5c9', '#d6a79c']
type Page = 'dashboard' | 'library' | 'preferences' | 'settings'
type Notify = (message: string, error?: boolean) => void

function Cover({ track, large = false }: { track: Track; large?: boolean }) {
  const [failed, setFailed] = useState(false)
  useEffect(() => setFailed(false), [track.id])
  const tone = parseInt(track.id.slice(0, 4), 16) % 4
  return <div className={`cover tone-${tone} ${large ? 'cover-large' : ''}`}>{track.has_cover && !failed ? <img src={`/api/tracks/${track.id}/cover`} alt={`${track.title}封面`} onError={() => setFailed(true)} /> : <><div className="cover-orbit"/><Music2 size={large ? 38 : 20}/></>}</div>
}
function Button({ icon: Icon, children, onClick, primary = false, disabled = false, className = '' }: { icon?: LucideIcon; children: React.ReactNode; onClick?: () => void; primary?: boolean; disabled?: boolean; className?: string }) {
  return <button className={`button ${primary ? 'primary' : ''} ${className}`} onClick={onClick} disabled={disabled}>{Icon && <Icon size={16}/>} {children}</button>
}
function Tag({ value, comfort = 35, high = 60 }: { value: number | null; comfort?: number; high?: number }) {
  if (value == null) return <span className="muted">待分析</span>
  return <span className={`tag ${value < comfort ? 'quiet' : value >= high ? 'loud' : 'moderate'}`}>{value < comfort ? '舒缓' : value >= high ? '较激烈' : '适中'}</span>
}
function Empty({ onUpload }: { onUpload: () => void }) {
  return <div className="empty"><div className="empty-icon"><AudioLines size={32}/></div><h3>让音乐，回到舒适的频率</h3><p>导入你的第一首音乐，探索整曲与每个片段的听感特征。</p><Button primary icon={Plus} onClick={onUpload}>导入音乐</Button><small>支持 MP3、FLAC、WAV、M4A、OGG · 每个文件最多 200 MB</small></div>
}
function activeScore(track: Track, personal: boolean) { return personal && track.personal_score != null ? track.personal_score : track.score?.combined ?? null }

export default function App() {
  const [page, setPage] = useState<Page>('dashboard')
  const [tracks, setTracks] = useState<Track[]>([])
  const [stats, setStats] = useState<Stats | null>(null)
  const [profile, setProfile] = useState<Profile | null>(null)
  const [settings, setSettings] = useState<Settings | null>(null)
  const [detail, setDetail] = useState<Track | null>(null)
  const [current, setCurrent] = useState<Track | null>(null)
  const [personal, setPersonal] = useState(false)
  const [theme, setTheme] = useState(() => window.quiettuneDesktop?.preferences.theme || localStorage.getItem('quiettune-theme') || 'dark')
  const [toast, setToast] = useState<{ message: string; error: boolean } | null>(null)
  const [connectionError, setConnectionError] = useState('')
  const [loading, setLoading] = useState(true)
  const [uploadProgress, setUploadProgress] = useState('')
  const [dragging, setDragging] = useState(false)
  const [q, setQ] = useState('')
  const fileRef = useRef<HTMLInputElement>(null)
  const folderRef = useRef<HTMLInputElement>(null)
  const audioRef = useRef<HTMLAudioElement>(null)
  const detailId = useRef<string | null>(null)
  const autoPlay = useRef(false)
  const [playing, setPlaying] = useState(false)
  const [position, setPosition] = useState(0)
  const [volume, setVolume] = useState(() => window.quiettuneDesktop?.preferences.volume ?? 0.65)
  const notice: Notify = useCallback((message, error = false) => setToast({ message, error }), [])
  const refresh = useCallback(async () => {
    try {
      const [list, summary, user, config] = await Promise.all([api<Track[]>('/tracks'), api<Stats>(`/stats?mode=${personal ? 'personal' : 'general'}`), api<Profile>('/profile'), api<Settings>('/settings')])
      setTracks(list); setStats(summary); setProfile(user); setSettings(config); setConnectionError('')
      if (detailId.current) {
        const data = await api<Track>(`/tracks/${detailId.current}`)
        setDetail(previous => previous?.id === data.id ? data : previous)
      }
    } catch (error) { setConnectionError((error as Error).message || '无法连接分析服务，请确认后端已启动。') }
    finally { setLoading(false) }
  }, [personal])
  useEffect(() => { void refresh() }, [refresh])
  const busy = tracks.some(t => t.status === 'queued' || t.status === 'running')
  useEffect(() => { if (!busy) return; const timer = setInterval(() => void refresh(), 2000); return () => clearInterval(timer) }, [busy, refresh])
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('quiettune-theme', theme) }, [theme])
  // 桌面服务使用随机端口，界面偏好由主进程保存，避免随页面来源变化而丢失。
  useEffect(() => { window.quiettuneDesktop?.savePreferences({ theme, volume }) }, [theme, volume])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 6000); return () => clearTimeout(timer) }, [toast])
  useEffect(() => {
    setPosition(0); setPlaying(false)
    if (autoPlay.current && audioRef.current) { void audioRef.current.play().catch(() => notice('请点击播放按钮开始试听。')); autoPlay.current = false }
  }, [current?.id, notice])
  useEffect(() => { if (audioRef.current) audioRef.current.volume = volume }, [volume])

  async function uploadFiles(files: FileList | File[]) {
    const supported = Array.from(files).filter(f => /\.(mp3|flac|wav|m4a|ogg)$/i.test(f.name))
    if (!supported.length) { notice('请选择支持的音频文件。', true); return }
    let imported = 0, duplicate = 0, failed = 0
    for (let index = 0; index < supported.length; index++) {
      const file = supported[index]
      setUploadProgress(`正在导入 ${index + 1}/${supported.length} · ${file.name}`)
      const form = new FormData(); form.append('file', file)
      try { const data = await api<{ duplicate: boolean }>(`/tracks?relative_path=${encodeURIComponent(file.webkitRelativePath || '')}`, { method: 'POST', body: form }); data.duplicate ? duplicate++ : imported++ }
      catch (error) { failed++; notice(`${file.name}：${(error as Error).message}`, true) }
      await refresh()
    }
    setUploadProgress(''); notice(`导入 ${imported} 首，已存在 ${duplicate} 首${failed ? `，失败 ${failed} 首` : ''}。`, failed > 0)
  }
  const onFiles = (event: ChangeEvent<HTMLInputElement>) => { if (event.target.files) void uploadFiles(event.target.files); event.target.value = '' }
  async function openTrack(track: Track, play = false) {
    try {
      const data = await api<Track>(`/tracks/${track.id}`)
      detailId.current = track.id; setDetail(data)
      if (current?.id !== track.id) { autoPlay.current = play; setCurrent(data) }
      else if (play) void audioRef.current?.play().catch(error => notice(error.message, true))
    } catch (error) { notice((error as Error).message, true) }
  }
  function changePage(next: Page) { setPage(next); setDetail(null); detailId.current = null }
  async function action(task: () => Promise<unknown>, message: string) {
    try { await task(); notice(message); await refresh() } catch (error) { notice((error as Error).message, true) }
  }
  function seek(seconds: number) { if (audioRef.current) { audioRef.current.currentTime = seconds; setPosition(seconds); void audioRef.current.play().catch(() => notice('请点击播放按钮试听该片段。')) } }
  const title = { dashboard: '总览', library: '音乐库', preferences: '偏好校准', settings: '分析设置' }[page]
  return <div className={`app${window.quiettuneDesktop ? ' desktop' : ''}`} onDragOver={e => { if (e.dataTransfer.types.includes('Files')) { e.preventDefault(); setDragging(true) } }} onDrop={e => { e.preventDefault(); setDragging(false); if (!uploadProgress) void uploadFiles(e.dataTransfer.files) }}>
    <input hidden ref={fileRef} type="file" multiple accept=".mp3,.flac,.wav,.m4a,.ogg" onChange={onFiles}/>
    <input hidden ref={folderRef} type="file" multiple {...{ webkitdirectory: '', directory: '' }} onChange={onFiles}/>
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); changePage('dashboard') }}><span className="brand-icon"><AudioLines size={23}/></span><div>QuietTune<small>音乐舒适度分析</small></div></a>
      <div className="nav-caption">你的音乐空间</div>
      <nav>{([{ id: 'dashboard', name: '总览', icon: LayoutDashboard }, { id: 'library', name: '音乐库', icon: Library }, { id: 'preferences', name: '偏好校准', icon: SlidersHorizontal }, { id: 'settings', name: '分析设置', icon: Settings2 }] as { id: Page; name: string; icon: LucideIcon }[]).map(({ id, name, icon: Icon }) => <button className={`nav-item ${page === id && !detail ? 'active' : ''}`} key={id} onClick={() => changePage(id)}><Icon size={19}/>{name}{id === 'library' && <span className="nav-count">{tracks.length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="local-state"><span className={connectionError ? 'status-dot offline' : 'status-dot'}/>{connectionError ? '服务未连接' : '本地分析服务'}<small>你的音乐，留在你的设备</small></div><button className="user-card" onClick={() => changePage('preferences')}><div className="avatar"><Headphones size={18} aria-hidden="true"/></div><div><strong>个人听觉偏好</strong><small>{profile?.feedback_count || 0} 首已评价</small></div><ChevronRight size={15}/></button></div>
    </aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumb">我的空间 <ChevronRight size={13}/> <span>{detail ? '单曲分析' : title}</span></div><div className="topbar-actions"><button className={`mode-switch ${personal ? 'selected' : ''}`} onClick={() => setPersonal(!personal)}><Sparkles size={14}/>{personal ? '个人评分' : '通用评分'}</button><button className="icon-button" aria-label={theme === 'dark' ? '切换浅色主题' : '切换深色主题'} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={18}/> : <Moon size={18}/>}</button><div className="avatar small"><Headphones size={18} aria-hidden="true"/></div>{window.quiettuneDesktop && <button className="icon-button" aria-label="应用菜单" title="应用菜单" onClick={() => void window.quiettuneDesktop?.menu()}><MoreHorizontal size={18}/></button>}</div></header>
      <main>
        {connectionError && <div role="alert" className="alert error">{connectionError}<button onClick={() => void refresh()}>重新连接</button></div>}
        {personal && profile?.status !== 'ready' && <div className="alert">个人模型尚未启用，当前展示通用指数。<button onClick={() => changePage('preferences')}>前往校准 <ArrowRight size={13}/></button></div>}
        {uploadProgress && <div role="status" className="alert"><Loader2 size={16} className="spin"/>{uploadProgress}</div>}
        {detail ? <Detail track={detail} audioRef={audioRef} position={position} personal={personal} settings={settings} seek={seek} back={() => { setDetail(null); detailId.current = null }} onFeedback={async data => action(() => send(`/tracks/${detail.id}/feedback`, data, 'PUT'), '评价已保存。')} onAnalyze={() => void action(() => send(`/tracks/${detail.id}/analyze`), '已加入分析队列。')} /> : loading ? <div className="loading"><Loader2 className="spin"/>正在连接你的音乐空间…</div> : page === 'dashboard' ? <Dashboard tracks={tracks} stats={stats} profile={profile} settings={settings} personal={personal} open={openTrack} upload={() => fileRef.current?.click()} library={() => changePage('library')} /> : page === 'library' ? <MusicLibrary tracks={tracks} settings={settings} personal={personal} q={q} setQ={setQ} open={openTrack} upload={() => fileRef.current?.click()} folder={() => folderRef.current?.click()} onAnalyze={ids => void action(() => send('/analyze', { track_ids: ids }), '已加入分析队列。')} onDelete={id => void action(async () => { await api(`/tracks/${id}`, { method: 'DELETE' }); if (current?.id === id) setCurrent(null) }, '歌曲已删除。')} /> : page === 'preferences' ? <Preferences tracks={tracks} profile={profile} open={openTrack} notify={notice} refresh={refresh} /> : settings && <SettingsPage initial={settings} refresh={refresh} notify={notice} onAnalyze={() => void action(() => send('/analyze', { track_ids: tracks.map(t => t.id) }), '全库已加入重新分析队列。')} hasTracks={tracks.length > 0} />}
      </main><footer className="page-footer"><span>QuietTune · 用数据，找到更舒服的音乐</span><span>指数为启发式估计，听感由你决定</span></footer>
    </div>
    <div className="player"><audio ref={audioRef} src={current ? `/api/tracks/${current.id}/audio` : undefined} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} onEnded={() => setPlaying(false)} onTimeUpdate={e => setPosition(e.currentTarget.currentTime)} onError={() => notice('浏览器无法播放该格式，或音频文件不可用。', true)} preload="metadata"/>
      <div className="player-track">{current ? <><Cover track={current}/><div><strong>{current.title}</strong><small>{current.artist}</small></div><Tag value={activeScore(current, personal)} comfort={settings?.comfort_threshold} high={settings?.threshold}/></> : <><div className="cover"><Music2 size={20}/></div><div><strong>还没有播放中的音乐</strong><small>选择一首，开始舒适的试听</small></div></>}</div>
      <div className="player-middle"><div className="transport"><button className="icon-button" aria-label="回到歌曲开头" disabled={!current} onClick={() => { if (audioRef.current) audioRef.current.currentTime = 0 }}><RefreshCw size={15}/></button><button className="play-button" aria-label={playing ? '暂停' : '播放'} disabled={!current} onClick={() => { const audio = audioRef.current; if (!audio) return; if (playing) audio.pause(); else void audio.play().catch(() => notice('音频暂时无法播放，请检查文件。', true)) }}>{playing ? <Pause size={18} fill="currentColor"/> : <Play size={18} fill="currentColor"/>}</button><button className="icon-button" aria-label="前进十秒" disabled={!current} onClick={() => { if (audioRef.current && current) audioRef.current.currentTime = Math.min(current.duration, position + 10) }}><ArrowRight size={16}/></button></div><div className="seek"><span>{time(position)}</span><input aria-label="播放进度" type="range" min={0} max={current?.duration || 1} step={0.1} value={position} disabled={!current} onChange={e => { if (audioRef.current) audioRef.current.currentTime = Number(e.target.value) }}/><span>{time(current?.duration || 0)}</span></div></div>
      <div className="volume"><Volume2 size={17}/><input aria-label="播放音量" type="range" min={0} max={1} step={0.01} value={volume} onChange={e => setVolume(Number(e.target.value))}/><span>本地播放</span></div>
    </div>
    {dragging && <div className="drop-overlay" onDragLeave={() => setDragging(false)}><Upload size={45}/><h2>松开，导入你的音乐</h2><p>我们会自动完成真实音频分析</p></div>}
    {toast && <div role="status" className={`toast ${toast.error ? 'error' : ''}`}>{toast.error ? <Activity size={17}/> : <Check size={17}/>}<span>{toast.message}</span><button aria-label="关闭提示" onClick={() => setToast(null)}><X size={16}/></button></div>}
  </div>
}

function Dashboard({ tracks, stats, profile, settings, personal, open, upload, library }: { tracks: Track[]; stats: Stats | null; profile: Profile | null; settings: Settings | null; personal: boolean; open: (track: Track, play?: boolean) => void; upload: () => void; library: () => void }) {
  const recommended = (stats?.recommendation_ids || []).map(id => tracks.find(t => t.id === id)).filter((t): t is Track => !!t)
  return <><div className="page-heading"><div><div className="eyebrow">聆听，更从容</div><h1>音乐舒适度总览<span className="heading-dot">.</span></h1><p>找到适合你的声音，让每一次聆听都恰到好处。</p></div><Button primary icon={Plus} onClick={upload}>导入音乐</Button></div>
    <section className="hero"><div className="hero-copy"><span className="pill"><Headphones size={14}/>为你的听感而设计</span><h2>好音乐，<br/>也可以很舒服。</h2><p>不只看音量。探索频谱、瞬态和情绪，<br/>慢慢了解你喜欢怎样的声音。</p><button className="text-button" onClick={library}>探索我的音乐库 <ArrowRight size={16}/></button></div><div className="hero-art" aria-hidden="true"><div className="art-circle outer"/><div className="art-circle middle"/><div className="art-circle inner"/><div className="art-center"><AudioLines size={62} strokeWidth={1.3}/></div><div className="float-label one"><span className="status-dot"/>多维声学分析</div><div className="float-label two"><Sparkles size={13}/>听感由你定义</div></div><span className="hero-index">QUIET / TUNE</span></section>
    <div className="stat-grid">{[{ icon: Music2, label: '音乐总数', value: stats?.total ?? 0, foot: `${stats?.analyzed || 0} 首已完成分析` }, { icon: Activity, label: '平均吵闹指数', value: number(stats?.average), foot: '0–100 · 多维综合评分' }, { icon: Headphones, label: '舒适音乐', value: stats?.comfortable ?? 0, foot: `低于 ${settings?.comfort_threshold || 35} 分` }, { icon: AudioLines, label: '较激烈音乐', value: stats?.high ?? 0, foot: `达到 ${settings?.threshold || 60} 分` }].map(({ icon: Icon, label, value, foot }) => <div className="stat-card" key={label}><div className="stat-label">{label}<Icon size={17}/></div><strong>{value}</strong><small>{foot}</small></div>)}</div>
    {!tracks.length ? <div className="panel"><Empty onUpload={upload}/></div> : <div className="dashboard-grid"><section className="panel"><div className="section-heading"><div><h3>最近导入</h3><p>每一首，都有自己的声音特征</p></div><button className="text-button muted" onClick={library}>全部音乐 <ArrowRight size={14}/></button></div><div className="recent-list">{tracks.slice(0, 5).map(track => <button className="recent-row" key={track.id} onClick={() => open(track)}><Cover track={track}/><div className="song-name"><strong>{track.title}</strong><small>{track.artist} · {time(track.duration)}</small></div>{track.score ? <><span className="row-score">{number(activeScore(track, personal), 0)}<small>/100</small></span><Tag value={activeScore(track, personal)} comfort={settings?.comfort_threshold} high={settings?.threshold}/></> : <span className="job-label">{track.status === 'failed' ? '分析失败' : track.job?.stage || '等待分析'}{track.status === 'running' && <Loader2 size={13} className="spin"/>}</span>}<ChevronRight size={16}/></button>)}</div></section>
      <section className="panel distribution"><div className="section-heading"><div><h3>吵闹程度分布</h3><p>看看你的音乐，落在哪个区间</p></div><MoreHorizontal size={18}/></div>{stats?.analyzed ? <><ResponsiveContainer width="100%" height={175}><BarChart data={stats.distribution} barSize={27} margin={{ left: -28, right: 8, top: 10, bottom: 0 }}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="name" tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 10 }} formatter={(value: number) => [`${value} 首`, '音乐数量']}/><Bar dataKey="count" radius={[5, 5, 0, 0]}>{colors.map(color => <Cell key={color} fill={color}/>)}</Bar></BarChart></ResponsiveContainer><div className="distribution-legend"><span>更舒缓</span><span>更激烈</span></div></> : <div className="chart-empty">分析完成后显示真实分布</div>}</section></div>}
    <div className="section-heading recommendations-heading"><div><h3>给耳朵，留一点轻松</h3><p>根据{personal && profile?.status === 'ready' ? '个人' : '通用'}指数，从音乐库中选择较舒缓的音乐</p></div><span className="pill subtle"><Sparkles size={13}/>舒适推荐</span></div>
    {recommended.length ? <div className="recommendations">{recommended.map(track => <button className="recommendation" key={track.id} onClick={() => open(track, true)}><div className="recommendation-art"><Cover track={track} large/><span className="recommendation-play"><Play size={18} fill="currentColor"/></span></div><div className="recommendation-info"><strong>{track.title}</strong><small>{track.artist}</small><div><Tag value={activeScore(track, personal)} comfort={settings?.comfort_threshold} high={settings?.threshold}/><span>{number(activeScore(track, personal), 0)}<small> 分</small></span></div></div></button>)}</div> : <div className="recommendation-empty"><Headphones size={20}/>完成分析后，这里会出现来自你音乐库的推荐。</div>}
    <div className="profile-strip"><div className="avatar"><Headphones size={18} aria-hidden="true"/></div><div><strong>越了解你，推荐越贴近你</strong><p>已评价 {profile?.feedback_count || 0} 首歌曲，{profile?.status === 'ready' ? '个人模型已启用。' : '积累至少 12 首、多种评价后尝试建立个人模型。'}</p></div><Sparkles size={22}/></div>
  </>
}

function MusicLibrary({ tracks, settings, personal, q, setQ, open, upload, folder, onAnalyze, onDelete }: { tracks: Track[]; settings: Settings | null; personal: boolean; q: string; setQ: (q: string) => void; open: (t: Track, play?: boolean) => void; upload: () => void; folder: () => void; onAnalyze: (ids: string[]) => void; onDelete: (id: string) => void }) {
  const [sort, setSort] = useState('recent'), [threshold, setThreshold] = useState(100), [artist, setArtist] = useState(''), [album, setAlbum] = useState('')
  const [selected, setSelected] = useState<string[]>([])
  const [deleteTrack, setDeleteTrack] = useState<Track | null>(null)
  const visible = tracks.filter(t => `${t.title} ${t.artist} ${t.album}`.toLowerCase().includes(q.toLowerCase()) && (!artist || t.artist === artist) && (!album || t.album === album) && ((activeScore(t, personal) == null && threshold === 100) || (activeScore(t, personal) != null && activeScore(t, personal)! <= threshold))).sort((a, b) => sort === 'score' ? (activeScore(a, personal) ?? 101) - (activeScore(b, personal) ?? 101) : sort === 'score_desc' ? (activeScore(b, personal) ?? -1) - (activeScore(a, personal) ?? -1) : sort === 'title' ? a.title.localeCompare(b.title, 'zh-CN') : b.created_at.localeCompare(a.created_at))
  return <><div className="page-heading"><div><div className="eyebrow">你的声音收藏</div><h1>音乐库<span className="heading-dot">.</span></h1><p>{tracks.length} 首音乐 · 按听感发现更适合自己的歌曲</p></div><div className="button-group"><Button icon={FolderOpen} onClick={folder}>导入文件夹</Button><Button primary icon={Plus} onClick={upload}>导入音乐</Button></div></div>
    <div className="upload-zone" onClick={upload} role="button" tabIndex={0} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') upload() }}><div className="upload-icon"><Upload size={22}/></div><div><strong>拖放音乐文件到这里，或点击导入</strong><p>批量上传后自动分析 · 支持 MP3、FLAC、WAV、M4A、OGG</p></div><Plus size={20}/></div>
    <section className="panel library-panel"><div className="library-toolbar"><div className="search-box"><Search size={16}/><input aria-label="搜索歌曲" placeholder="搜索歌曲、艺术家或专辑" value={q} onChange={e => setQ(e.target.value)}/></div><select aria-label="排序方式" value={sort} onChange={e => setSort(e.target.value)}><option value="recent">最近导入</option><option value="score">吵闹指数：从低到高</option><option value="score_desc">吵闹指数：从高到低</option><option value="title">歌曲名称</option></select><a className="button" href="/api/export.csv"><ArrowDownToLine size={15}/>导出 CSV</a></div>
      <div className="filter-row"><SlidersHorizontal size={15}/><span>筛选</span><select aria-label="艺术家筛选" value={artist} onChange={e => setArtist(e.target.value)}><option value="">所有艺术家</option>{Array.from(new Set(tracks.map(t => t.artist))).map(a => <option key={a}>{a}</option>)}</select><select aria-label="专辑筛选" value={album} onChange={e => setAlbum(e.target.value)}><option value="">所有专辑</option>{Array.from(new Set(tracks.map(t => t.album))).map(a => <option key={a}>{a}</option>)}</select><label>指数 ≤ <strong>{threshold}</strong><input aria-label="吵闹指数上限" type="range" min={0} max={100} value={threshold} onChange={e => setThreshold(Number(e.target.value))}/></label><span className="filter-count">{visible.length} 首符合条件</span></div>
      {!!selected.length && <div className="selection-bar"><span>已选择 {selected.length} 首</span><Button icon={RefreshCw} onClick={() => { onAnalyze(selected.filter(id => tracks.some(t => t.id === id))); setSelected([]) }}>批量分析</Button><button onClick={() => setSelected([])}>取消选择</button></div>}
      {!tracks.length ? <Empty onUpload={upload}/> : !visible.length ? <div className="chart-empty">没有符合条件的歌曲，试试放宽筛选条件。</div> : <div className="table-wrap"><table><thead><tr><th><input aria-label="选择全部筛选歌曲" type="checkbox" checked={visible.length > 0 && visible.every(t => selected.includes(t.id))} onChange={e => setSelected(e.target.checked ? visible.map(t => t.id) : [])}/></th><th>歌曲</th><th>专辑</th><th>时长</th><th>{personal ? '个人指数' : '吵闹指数'}</th><th>听感</th><th>操作</th></tr></thead><tbody>{visible.map(track => <tr key={track.id}><td><input aria-label={`选择${track.title}`} type="checkbox" checked={selected.includes(track.id)} onChange={e => setSelected(e.target.checked ? [...selected, track.id] : selected.filter(id => id !== track.id))}/></td><td><button className="table-song" onClick={() => open(track)}><Cover track={track}/><div><strong>{track.title}</strong><small>{track.artist}</small></div></button></td><td className="muted">{track.album}</td><td className="muted mono">{time(track.duration)}</td><td>{track.score ? <div className="score-cell"><strong>{number(activeScore(track, personal), 0)}</strong><div className="mini-meter"><span style={{ width: `${activeScore(track, personal)}%`, background: colors[Math.min(4, Math.floor((activeScore(track, personal) || 0) / 20))] }}/></div></div> : <div className="job-cell"><span className={track.status === 'failed' ? 'error-text' : 'muted'}>{track.job?.stage || '待分析'}</span>{track.status === 'running' && <progress max={100} value={track.job?.progress || 0}/>}</div>}</td><td><Tag value={activeScore(track, personal)} comfort={settings?.comfort_threshold} high={settings?.threshold}/></td><td><div className="row-actions"><button aria-label={`播放${track.title}`} onClick={() => open(track, true)}><Play size={15}/></button><button aria-label={`重新分析${track.title}`} onClick={() => onAnalyze([track.id])}><RefreshCw size={15}/></button><button aria-label={`删除${track.title}`} onClick={() => setDeleteTrack(track)} disabled={track.status === 'queued' || track.status === 'running'}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}
    </section>{deleteTrack && <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h3 id="delete-title">删除「{deleteTrack.title}」？</h3><p>这会移除本地导入副本、分析结果与评价。原始音乐文件仍在你的电脑中。</p><div className="button-group"><Button onClick={() => setDeleteTrack(null)}>取消</Button><Button primary icon={Trash2} onClick={() => { onDelete(deleteTrack.id); setDeleteTrack(null) }}>删除歌曲</Button></div></div></div>}
  </>
}

function Detail({ track, audioRef, position, personal, settings, seek, back, onFeedback, onAnalyze }: { track: Track; audioRef: RefObject<HTMLAudioElement | null>; position: number; personal: boolean; settings: Settings | null; seek: (s: number) => void; back: () => void; onFeedback: (data: { rating: number; factors: string[]; note: string }) => Promise<void>; onAnalyze: () => void }) {
  const waveformRef = useRef<HTMLDivElement>(null)
  const [rating, setRating] = useState(track.feedback?.rating || 0), [selectedFactors, setSelectedFactors] = useState(track.feedback?.factors || []), [note, setNote] = useState(track.feedback?.note || ''), [saving, setSaving] = useState(false)
  const feature = track.features, scored = track.score
  useEffect(() => {
    if (!waveformRef.current || !feature?.waveform || !audioRef.current) return
    const wave = WaveSurfer.create({ container: waveformRef.current, media: audioRef.current, peaks: [feature.waveform], duration: track.duration, height: 80, barWidth: 2, barGap: 2, barRadius: 2, waveColor: '#536467', progressColor: '#9bcbc2', cursorColor: '#c0ddd0', normalize: true, interact: true })
    return () => wave.destroy()
  }, [track.id, feature?.waveform?.length, audioRef])
  async function save() { setSaving(true); try { await onFeedback({ rating, factors: selectedFactors, note }) } finally { setSaving(false) } }
  return <><button className="back-button" onClick={back}><ArrowLeft size={16}/>返回音乐空间</button><section className="detail-header"><Cover track={track} large/><div className="detail-title"><div className="eyebrow">单曲听感档案</div><h1>{track.title}</h1><p>{track.artist}<span>·</span>{track.album}<span>·</span><Clock3 size={13}/>{time(track.duration)}</p><div className="detail-badges"><Tag value={activeScore(track, personal)} comfort={settings?.comfort_threshold} high={settings?.threshold}/><span className="pill subtle">{scored?.mode || '等待分析'}</span></div><div className="button-group"><Button primary icon={Play} onClick={() => seek(position)}>试听音乐</Button><Button icon={RefreshCw} onClick={onAnalyze}>重新分析</Button></div></div><div className="main-score"><div className="score-ring" style={{ '--score': `${activeScore(track, personal) ?? 0}%` } as React.CSSProperties}><strong>{number(activeScore(track, personal), 0)}</strong><span>/ 100</span></div><p>{personal && track.personal_score != null ? '个人吵闹指数' : '通用吵闹指数'}</p></div></section>
    {track.job?.error && <div className="alert error">分析失败：{track.job.error}<button onClick={onAnalyze}>重试</button></div>}
    {!scored || !feature ? <section className="panel empty"><Loader2 className={track.status === 'failed' ? '' : 'spin'}/><h3>{track.job?.stage || '等待分析'}</h3><p>后台提取真实特征后会在这里显示结果。</p><progress max={100} value={track.job?.progress || 0}/></section> : <><section className="panel timeline"><div className="section-heading"><div><h3>听见每个片段的变化</h3><p>点击波形、曲线或片段，跳转试听 · 窗口 {feature.provenance.window_seconds} 秒</p></div><span className="pill subtle"><span className="status-dot"/>分段声学指数</span></div><div ref={waveformRef} className="waveform"/><div className="heatmap">{scored.segments?.map(segment => <button aria-label={`试听${time(segment.start)}到${time(segment.end)}，指数${segment.score.toFixed(0)}`} key={segment.start} onClick={() => seek(segment.start)} style={{ flex: segment.end - segment.start, background: colors[Math.min(4, Math.floor(segment.score / 20))] }} title={`${time(segment.start)}–${time(segment.end)} · ${number(segment.score)} 分`}/>)}</div><div className="timeline-labels"><span>00:00</span><span>正在播放 {time(position)}</span><span>{time(track.duration)}</span></div><ResponsiveContainer width="100%" height={190}><AreaChart data={scored.segments} onClick={event => { const value = event?.activePayload?.[0]?.payload; if (value) seek(value.start) }} margin={{ left: -22, right: 15, top: 18, bottom: 0 }}><defs><linearGradient id="scoreFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#a5c6bb" stopOpacity={0.35}/><stop offset="100%" stopColor="#a5c6bb" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="start" tickFormatter={time} tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis domain={[0, 100]} tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)', borderRadius: 10 }} labelFormatter={value => time(Number(value))} formatter={(value: number) => [number(value) + ' 分', '声学指数']}/><Area dataKey="score" type="linear" stroke="#a5c6bb" strokeWidth={2} fill="url(#scoreFill)"/></AreaChart></ResponsiveContainer><div className="timeline-summary"><div><small>全曲综合均值</small><strong>{number(scored.average)}<span>分</span></strong></div><div><small>峰值声学片段</small><strong>{number(scored.peak)}<span>分</span></strong></div><div><small>高吵闹片段占比</small><strong>{number(scored.high_ratio * 100, 0)}<span>%</span></strong></div><button className="peak-link" onClick={() => seek(scored.loudest.start)}><Play size={16}/>试听最高片段<small>{time(scored.loudest.start)}–{time(scored.loudest.end)}</small></button></div></section>
      <section className="feature-grid">{[{ title: '综合响度', value: number(feature.lufs), unit: 'LUFS', note: 'EBU R128 · 原始母带' }, { title: '节拍速度', value: number(feature.bpm, 0), unit: 'BPM', note: '仅作参考，不直接决定指数' }, { title: '高频能量占比', value: number(feature.high_frequency_ratio * 100), unit: '%', note: '4 kHz 以上 · 刺激性代理' }, { title: '瞬态事件密度', value: number(feature.onset_density, 2), unit: '次/秒', note: '检测到的能量起始事件' }].map(item => <div className="stat-card" key={item.title}><div className="stat-label">{item.title}<Activity size={15}/></div><strong>{item.value}<span className="unit">{item.unit}</span></strong><small>{item.note}</small></div>)}</section>
      <div className="detail-grid"><section className="panel"><div className="section-heading"><div><h3>为什么是这个分数？</h3><p>来自真实特征的可解释结果</p></div><SlidersHorizontal size={18}/></div><div className="dimension-list">{Object.entries(scored.dimensions).map(([key, value]) => <div className="dimension" key={key}><span>{dimensionLabels[key as Dimension]}</span><div className="dimension-meter"><span style={{ width: `${value! * 100}%` }}/></div><strong>{number(value! * 100, 0)}</strong></div>)}</div><ul className="reason-list">{scored.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul><small className="footnote">归一化代理指标 ≠ 人类感知。指数不是标准物理单位。</small></section>
        <section className="panel"><div className="section-heading"><div><h3>音乐情绪预测</h3><p>官方独立分类器 · 整曲输出</p></div><Sparkles size={18}/></div>{feature.ai.status === 'ready' ? <><div className="emotion-row"><span>激烈程度</span><strong>{number(feature.ai.aggressive! * 100)}<small>%</small></strong></div><div className="emotion-meter"><span style={{ width: `${feature.ai.aggressive! * 100}%`, background: '#c0a8cb' }}/></div><div className="emotion-row"><span>放松程度</span><strong>{number(feature.ai.relaxed! * 100)}<small>%</small></strong></div><div className="emotion-meter"><span style={{ width: `${feature.ai.relaxed! * 100}%` }}/></div><p className="footnote">两个概率独立计算，合计无需为 100%。不会将整曲概率复制到局部片段。</p><div className="model-credit"><span>{feature.ai.runtime}</span><small>MusiCNN · {feature.ai.patches} 个输入片段</small>{feature.ai.models && Object.entries(feature.ai.models).map(([key, model]) => <small key={key}>{model.name} · 元数据版本 {model.metadata_version}</small>)}</div></> : <div className="model-unavailable"><Activity size={25}/><strong>AI 情绪预测暂不可用</strong><p>{feature.ai.reason}</p><small>当前评分基于真实声学特征。安装或诊断步骤见项目说明。</small></div>}</section></div>
      <div className="detail-grid"><section className="panel"><div className="section-heading"><div><h3>频段能量分布</h3><p>各频段在全曲频谱中的能量比例</p></div></div><div className="frequency-bars">{['低频 0–250 Hz', '中频 250–2000 Hz', '中高频 2–4 kHz', '高频 4–11 kHz'].map((name, i) => <div key={name}><span>{name}</span><div><span style={{ width: `${feature.band_energy[i] * 100}%`, background: colors[i] }}/></div><strong>{number(feature.band_energy[i] * 100)}%</strong></div>)}</div><div className="extra-metrics"><span>频谱质心 <strong>{number(feature.centroid_hz, 0)} Hz</strong></span><span>频谱滚降 <strong>{number(feature.rolloff_hz, 0)} Hz</strong></span><span>频谱平坦度 <strong>{number(feature.flatness, 3)}</strong></span><span>RMS <strong>{number(feature.rms_dbfs)} dBFS</strong></span><span>真峰值 <strong>{number(feature.true_peak_dbfs)} dBFS</strong></span><span>峰均比 <strong>{number(feature.crest_db)} dB</strong></span></div></section><section className="panel"><div className="section-heading"><div><h3>短时响度变化</h3><p>3 秒响度窗口 · LUFS</p></div></div>{feature.short_term_loudness?.length ? <ResponsiveContainer width="100%" height={185}><AreaChart data={feature.short_term_loudness} margin={{ left: -15, right: 8 }}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="time" tickFormatter={time} tick={{ fill: 'var(--muted)', fontSize: 10 }}/><YAxis tick={{ fill: 'var(--muted)', fontSize: 10 }}/><Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)' }} labelFormatter={value => time(Number(value))} formatter={(value: number) => [`${number(value)} LUFS`, '短时响度']}/><Area dataKey="lufs" type="linear" fill="#aaa6ce" fillOpacity={0.15} stroke="#aaa6ce"/></AreaChart></ResponsiveContainer> : <div className="chart-empty">静音或时长不足时，短时响度可能无法测量。</div>}</section></div>
    </>}
    <section className="panel feedback-panel"><div className="section-heading"><div><h3>这首歌听起来怎么样？</h3><p>你的真实感受，会慢慢成为个人偏好的依据</p></div><div className="avatar"><Headphones size={18} aria-hidden="true"/></div></div><div className="rating-options">{labels.map((label, index) => <button className={rating === index + 1 ? 'selected' : ''} key={label} onClick={() => setRating(index + 1)}><span className="rating-dot" style={{ background: colors[index] }}/>{label}</button>)}</div><div className="feedback-factors"><span>不喜欢的因素（可多选）</span><div>{factors.map(factor => <button className={selectedFactors.includes(factor) ? 'selected' : ''} key={factor} onClick={() => setSelectedFactors(selectedFactors.includes(factor) ? selectedFactors.filter(f => f !== factor) : [...selectedFactors, factor])}>{factor}</button>)}</div></div><textarea aria-label="补充听感" placeholder="也可以写下你的感受，例如某个片段让你不太舒服…" maxLength={2000} value={note} onChange={e => setNote(e.target.value)}/><div className="feedback-footer"><span>{track.feedback ? '已有评价，可随时修改' : '评价只保存在本地'}</span><Button primary icon={saving ? Loader2 : Check} disabled={!rating || saving} onClick={() => void save()}>{saving ? '保存中…' : '保存我的评价'}</Button></div></section>
    {feature && <div className="provenance">分析器 {feature.provenance.analyzer} · 采样率 {feature.provenance.sample_rate} Hz · 评分版本 {track.scoring_version} · 分析时间 {track.analyzed_at ? new Date(track.analyzed_at).toLocaleString('zh-CN') : '—'}</div>}
  </>
}

function Preferences({ tracks, profile, open, notify, refresh }: { tracks: Track[]; profile: Profile | null; open: (t: Track, play?: boolean) => void; notify: Notify; refresh: () => Promise<void> }) {
  const [training, setTraining] = useState(false)
  const [candidateIndex, setCandidateIndex] = useState(0)
  const candidates = tracks.filter(t => t.score && !t.feedback)
  const candidate = candidates[candidateIndex % Math.max(1, candidates.length)]
  const evaluated = tracks.filter(t => t.feedback && t.score)
  async function train() { setTraining(true); try { const result = await send<Profile>('/profile/train'); notify(result.reason || '个人模型训练完成。'); await refresh() } catch (error) { notify((error as Error).message, true) } finally { setTraining(false) } }
  async function rate(rating: number) { if (!candidate) return; try { await send(`/tracks/${candidate.id}/feedback`, { rating, factors: [], note: '' }, 'PUT'); notify('评价已保存，继续听听下一首。'); await refresh() } catch (error) { notify((error as Error).message, true) } }
  const stateLabel = profile?.status === 'ready' ? '已启用个人模型' : profile?.status === 'stale' ? '等待重新训练' : profile?.status === 'rejected' ? '需要更多多样评价' : '正在积累偏好'
  return <><div className="page-heading"><div><div className="eyebrow">找到你喜欢的声音</div><h1>偏好校准<span className="heading-dot">.</span></h1><p>没有标准答案。舒服或不舒服，都由你的耳朵决定。</p></div><Button primary icon={training ? Loader2 : Sparkles} disabled={training} onClick={() => void train()}>{training ? '正在验证模型…' : '训练个人模型'}</Button></div>
    <div className="stat-grid"><div className="stat-card"><div className="stat-label">已评价音乐<Check size={17}/></div><strong>{profile?.feedback_count || 0}</strong><small>每首歌曲保留最新评价</small></div><div className="stat-card"><div className="stat-label">个人模型<Sparkles size={17}/></div><strong className="text-value">{stateLabel}</strong><small>至少 12 首歌曲，覆盖 3 种评价</small></div><div className="stat-card"><div className="stat-label">验证平均误差<Activity size={17}/></div><strong>{number(profile?.cv_mae)}<span className="unit">分</span></strong><small>四折交叉验证 · 0–100 量表</small></div><div className="stat-card"><div className="stat-label">均值基线误差<SlidersHorizontal size={17}/></div><strong>{number(profile?.baseline_mae)}<span className="unit">分</span></strong><small>模型优于基线后才启用</small></div></div>
    <div className="alert"><Sparkles size={16}/>{profile?.reason || '个人模型使用正则化回归，样本不足时继续使用通用规则。'}</div>
    <div className="detail-grid"><section className="panel calibration"><div className="section-heading"><div><h3>一首一首，了解你的偏好</h3><p>试听后，选一个最接近你的感受</p></div><span className="pill subtle">{candidates.length} 首待评价</span></div>{candidate ? <><div className="calibration-track"><Cover track={candidate} large/><div><h2>{candidate.title}</h2><p>{candidate.artist} · {time(candidate.duration)}</p><Button icon={Play} onClick={() => open(candidate, true)}>试听并查看片段</Button></div></div><div className="rating-options compact">{labels.map((label, i) => <button key={label} onClick={() => void rate(i + 1)}><span className="rating-dot" style={{ background: colors[i] }}/>{label}</button>)}</div><button className="text-button" onClick={() => setCandidateIndex(candidateIndex + 1)}>换一首候选音乐 <ArrowRight size={14}/></button></> : <div className="chart-empty"><Headphones size={26}/><p>当前没有未评价的已分析音乐。</p></div>}</section><section className="panel"><div className="section-heading"><div><h3>我的评价分布</h3><p>真实反馈，不替你判断听感</p></div></div><ResponsiveContainer width="100%" height={210}><BarChart data={labels.map((name, i) => ({ name, count: profile?.distribution[i] || 0 }))} barSize={28} margin={{ left: -28, right: 5 }}><CartesianGrid vertical={false} stroke="var(--line)"/><XAxis dataKey="name" tick={{ fill: 'var(--muted)', fontSize: 10 }} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{ fill: 'var(--muted)', fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip contentStyle={{ background: 'var(--surface)', border: '1px solid var(--line)' }} formatter={(v: number) => [`${v} 首`, '评价数量']}/><Bar dataKey="count" radius={[5, 5, 0, 0]}>{colors.map(color => <Cell key={color} fill={color}/>)}</Bar></BarChart></ResponsiveContainer></section></div>
    <section className="panel"><div className="section-heading"><div><h3>自动评分与真实感受</h3><p>主观量表映射：非常舒适 0 分 → 非常吵 100 分</p></div></div>{evaluated.length ? <div className="table-wrap"><table><thead><tr><th>歌曲</th><th>通用指数</th><th>主观评价</th><th>个人指数</th><th>通用指数与主观差异</th></tr></thead><tbody>{evaluated.map(track => <tr key={track.id}><td><button className="table-song" onClick={() => open(track)}><Cover track={track}/><strong>{track.title}</strong></button></td><td>{number(track.score!.combined)}</td><td>{labels[track.feedback!.rating - 1]}</td><td>{number(track.personal_score)}</td><td className="muted">{number(Math.abs(track.score!.combined - (track.feedback!.rating - 1) * 25))} 分</td></tr>)}</tbody></table></div> : <div className="chart-empty">第一次评价后，这里会展示评分差异。</div>}</section>
  </>
}

function SettingsPage({ initial, refresh, notify, onAnalyze, hasTracks }: { initial: Settings; refresh: () => Promise<void>; notify: Notify; onAnalyze: () => void; hasTracks: boolean }) {
  const [config, setConfig] = useState(initial), [saving, setSaving] = useState(false), [requiresAnalysis, setRequiresAnalysis] = useState(false)
  async function save(reset = false) {
    setSaving(true)
    try { const result = await send<{ message: string; requires_reanalysis: boolean }>(reset ? '/settings/reset' : '/settings', reset ? undefined : config, reset ? 'POST' : 'PUT'); notify(result.message); setRequiresAnalysis(result.requires_reanalysis); const data = await api<Settings>('/settings'); setConfig(data); await refresh() }
    catch (error) { notify((error as Error).message, true) } finally { setSaving(false) }
  }
  return <><div className="page-heading"><div><div className="eyebrow">让分析贴近你的使用方式</div><h1>分析设置<span className="heading-dot">.</span></h1><p>评分权重即时应用，声学特征始终可以复用。</p></div><div className="button-group"><Button icon={RefreshCw} disabled={saving} onClick={() => void save(true)}>恢复默认</Button><Button primary icon={Check} disabled={saving} onClick={() => void save()}>保存设置</Button></div></div>
    {requiresAnalysis && <div className="alert">窗口或 AI 配置已改变，已缓存结果保留原始分析参数。<button disabled={!hasTracks} onClick={onAnalyze}>重新分析音乐库</button></div>}
    <div className="detail-grid"><section className="panel"><div className="section-heading"><div><h3>综合评分权重</h3><p>启发式参考权重，系统按可用维度归一化</p></div><SlidersHorizontal size={18}/></div><div className="settings-sliders">{Object.entries(dimensionLabels).map(([key, label]) => <label key={key}><span>{label}<strong>{number(config.weights[key as Dimension] * 100, 0)}%</strong></span><input aria-label={`${label}权重`} type="range" min={0} max={1} step={0.01} value={config.weights[key as Dimension]} onChange={e => setConfig({ ...config, weights: { ...config.weights, [key]: Number(e.target.value) } })}/></label>)}<label><span>峰值片段额外影响<strong>{number(config.peak_mix * 100, 0)}%</strong></span><input aria-label="峰值影响" type="range" min={0} max={0.6} step={0.01} value={config.peak_mix} onChange={e => setConfig({ ...config, peak_mix: Number(e.target.value) })}/></label></div><p className="footnote">平均综合指数 + 峰值权重 × 正向峰值差。BPM 只作参考；关闭 AI 时，仅对可用声学维度重新归一化。</p></section><section className="panel"><div className="section-heading"><div><h3>分析与筛选</h3><p>保存后应用于新任务与评分</p></div><Settings2 size={18}/></div><div className="setting-row"><div><strong>舒适音乐阈值</strong><small>低于此值标记为舒缓</small></div><input aria-label="舒适阈值" type="number" min={0} max={99} value={config.comfort_threshold} onChange={e => setConfig({ ...config, comfort_threshold: Number(e.target.value) })}/></div><div className="setting-row"><div><strong>高吵闹阈值</strong><small>达到此值标记为较激烈</small></div><input aria-label="高吵闹阈值" type="number" min={1} max={100} value={config.threshold} onChange={e => setConfig({ ...config, threshold: Number(e.target.value) })}/></div><div className="setting-row"><div><strong>分析窗口</strong><small>更短窗口呈现更多局部变化</small></div><select aria-label="分析窗口" value={config.window_seconds} onChange={e => setConfig({ ...config, window_seconds: Number(e.target.value) as Settings['window_seconds'] })}>{[5, 10, 15, 30].map(value => <option key={value} value={value}>{value} 秒</option>)}</select></div><div className="setting-row"><div><strong>同时分析任务</strong><small>普通电脑建议 1 个；AI 推理串行</small></div><select aria-label="任务并发" value={config.concurrency} onChange={e => setConfig({ ...config, concurrency: Number(e.target.value) })}>{[1, 2, 3, 4].map(value => <option key={value} value={value}>{value} 个</option>)}</select></div><div className="setting-row"><div><strong>官方 AI 情绪模型</strong><small>激烈与放松，两个独立预测</small></div><button role="switch" aria-label="启用AI模型" aria-checked={config.ai_enabled} className={`toggle ${config.ai_enabled ? 'on' : ''}`} onClick={() => setConfig({ ...config, ai_enabled: !config.ai_enabled })}><span/></button></div></section></div>
    <section className="panel"><div className="section-heading"><div><h3>本地资源与模型</h3><p>音乐文件与分析数据库分开存储</p></div><FolderOpen size={18}/></div><div className="resource-grid"><div><span>音乐与数据库目录</span><code>{config.storage_path}</code></div><div><span>模型缓存目录</span><code>{config.model_path}</code></div><div><span>推理运行环境</span><strong>{config.model_status?.runtime}</strong></div><div><span>官方模型资源</span><strong>{config.model_status?.status === 'available' ? '权重与元数据已缓存' : '模型文件尚未齐全'}</strong></div></div><p className="footnote">迁移目录时，停止服务、移动数据，并在启动环境中设置 QUIETTUNE_DATA 与 QUIETTUNE_MODELS 后重启，避免数据库与文件路径不一致。具体迁移步骤见中文部署说明。</p></section>
  </>
}
