#!/usr/bin/env python

Import('ran_scripts')
if 'test/src/unittest/SConscript' in ran_scripts: Return()
ran_scripts.append('test/src/unittest/SConscript')

import os
from os.path import join

Import('env', 'source_tree_path', 'build_sh_cmd')
env = env.Clone()

### Run dependencies ###
SConscript(join(source_tree_path,'src','python','SConscript'))


### Create the alias ###
env.Alias('run_python_tests', 'python_install')
runCmd = build_sh_cmd(env, 'pytests_cmd', 'python', [ join(os.getcwd(),'all_tests.py'), 'barkbands' ], local=False)
AlwaysBuild(runCmd)
env.Alias('run_python_tests', runCmd)
