name: Build Python wheels (cibuildwheel)

on: [push, pull_request]

jobs:
  build_wheels:
    name: ${{ matrix.os }} / ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, macos-15]
        config: [cibuildwheel, cibuildwheel-tensorflow]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch release tags from GitHub
        # Workaround for https://github.com/actions/checkout/issues/290
        run: git fetch --tags --force

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          config-file: ${{ matrix.config }}.toml

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: artifact-${{ matrix.os }}-${{ matrix.config }}
